In [1]:
import numpy as np

In [3]:
one_dim_arr = np.array([1,2,3,4,5])
two_dim_arr = np.array([[1,2,3,4,5],[3,3,4,6,7]])
three_dim_arr = np.array([[[1,2,3,4,5]],[[3,3,4,6,7]]])

In [4]:
one_dim_arr.shape, two_dim_arr.shape, three_dim_arr.shape

((5,), (2, 5), (2, 1, 5))

In [5]:
one_dim_arr.ndim, two_dim_arr.ndim, three_dim_arr.ndim

(1, 2, 3)

In [7]:
import pandas as pd
data = pd.DataFrame({"account":one_dim_arr, "dimension":one_dim_arr})
data

account  dimension
0        1          1
1        2          2
2        3          3
3        4          4
4        5          5

In [8]:
one = np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
zeroes = np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
arr = np.arange(0,100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [13]:
a2 = np.random.randint(0,10,size=(7,2))
a2

array([[2, 3],
       [0, 7],
       [2, 7],
       [1, 7],
       [9, 7],
       [9, 5],
       [5, 3]])

In [15]:
a3=np.random.rand(3,5)
a3

array([[0.05278627, 0.40276856, 0.77123655, 0.58896243, 0.5800459 ],
       [0.95477885, 0.68117171, 0.09357802, 0.43810385, 0.78209626],
       [0.28805441, 0.697992  , 0.15321666, 0.00303355, 0.45913673]])

In [16]:
a4 = np.random.randint(1,10, size=(3,7))
a4

array([[3, 1, 2, 9, 2, 6, 4],
       [5, 9, 2, 7, 2, 1, 6],
       [9, 5, 7, 1, 7, 4, 7]])

In [17]:
np.unique(a4)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [18]:
a4[0]

array([3, 1, 2, 9, 2, 6, 4])

In [19]:
a4[:2]

array([[3, 1, 2, 9, 2, 6, 4],
       [5, 9, 2, 7, 2, 1, 6]])

In [20]:
a4[:2, :2]

array([[3, 1],
       [5, 9]])

In [21]:
rand_arr = np.random.randint(0,10, size=(3,5))
new_ones = np.ones((3,5))
rand_arr, new_ones

(array([[6, 1, 6, 7, 3],
        [4, 0, 2, 8, 2],
        [3, 9, 4, 4, 9]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [23]:
rand_arr + new_ones

array([[ 7.,  2.,  7.,  8.,  4.],
       [ 5.,  1.,  3.,  9.,  3.],
       [ 4., 10.,  5.,  5., 10.]])

In [25]:
sum(rand_arr, new_ones)

array([[14., 11., 13., 20., 15.],
       [14., 11., 13., 20., 15.],
       [14., 11., 13., 20., 15.]])

In [36]:
np.add(rand_arr, new_ones).std(), np.add(rand_arr, new_ones).mean()

(2.7535835237417845, 5.533333333333333)

In [27]:
a6 = np.ones((3,5))
a6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])